import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Sidebar from "../components/Sidebar/Sidebar"
import ConversationList from '../components/ConversationList/ConversationList'
import ChatView from '../components/ChatView/ChatView'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Discord CLone ZC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <Sidebar/>
        {/* Sidebar */}
        <div className={styles.main}>
          <ConversationList/>
          {/* conversationList */}
          {/* chat view */}
          <ChatView/>
        </div>
      </div>

      

      
    </div>
  )
}
